### ISSUE TITLE
Uglify issue moving from 5.3.x to 5.4

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/nativescript-cli#4641]
I just updated a 5.3.x app to 5.4. When creating a new build after deleting `node_modules` and `platforms`, this error was thrown:

`Error: Cannot find module 'uglifyjs-webpack-plugin'`

I didn't realize that I had to delete my `webpack.config.js` file as well.

Just a suggestion for improving this update workflow before 6.0!

**Comment by NL33** [comment]
Hi @rdlauer! I have been having these issues too. Didn't follow what you meant: when going from 5.3.x to 5.4, I have to DELETE my webpack.config.js? That seems odd, especially because I have some env. variables saved there. Any help is appreciated. THanks.

**Comment by NL33** [comment]
Just to follow-up on this, I was eventually able to get 5.4 to work and also to go back to 5.3.

The blank screen behavior was mostly from an error in the ts file of the home page component. Or, if not an error quite, something that the app did not like on load. So I went through the ts file and removed a bunch of stuff, got it to work, and then added in items from there to find what the issue was.

To get things back to a working version with 5.3, I went to the package.json file of an earlier version of my app that worked with 5.3, and basically went line by line down it to make sure I had the exact same versions as what appeared there. If I didn't have the exact version, I would change to that version with $ npm install [item]@[version]. 

To get 5.4 to work, I followed the steps outlined in the earlier comment; deleting node_modules, platforms, and webpack.config.js, then updating, etc...

However for now I have stuck with 5.3. I have found, as of this writing, 5.3 to perform slightly better than 5.4. Admittedly it could have been from other factors, but my app used more CPU and restarted a few times during use with 5.4, behaviors I never saw with 5.3. 

I also read in another comment that 5.4 was not allowing publishing to the iOS app store with $ tns publish.... That is a significant change in behavior. I recommend that the NS team make any issue like that very clear in the notes accompanying any new release, so developers can understand the kind of problem that might ensue with moving to 5.4.

So I switched back to 5.3 to be safe.
