### ISSUE TITLE
Error when executing "tns run ios" with 3.0 on a project that is located in a directory path with "spaces"

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-cli#2764]
### Did you verify this is a real problem by searching [Stack Overflow]
Yes, until now there has not been such thread.

### Tell us about the problem
After upgrading to NativeScript 3.0, running my migrated to 3.0 project on iOS that was running ok with the "rc" NativeScript throws the following error:

> ** BUILD SUCCEEDED **
> 
> Project successfully built.
> Installing...
> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
> Failed to install the requested application
> An application bundle was not found at the provided path.
> Provide a valid path to the desired application bundle.
> Multiple errors were thrown:
> Error Command failed: xcrun simctl install BB045E4E-57A0-44B2-B0F0-65BA885B09FD /Users/amiorkov/Desktop/Work/work _projs/sdkAngular/platforms/ios/build/emulator/sdkAngular.app
> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
> Failed to install the requested application
> An application bundle was not found at the provided path.
> Provide a valid path to the desired application bundle.
>  while executing xcrun simctl install BB045E4E-57A0-44B2-B0F0-65BA885B09FD /Users/amiorkov/Desktop/Work/work _projs/sdkAngular/platforms/ios/build/emulator/sdkAngular.app.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: (3.0.0
- Cross-platform modules: 3.0.0
- Runtime(s): 3.0.0
- XCode: 8.2.1
- Plugin(s): 
```
"dependencies": {
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "nativescript-angular": "3.0.0",
    "nativescript-fresco": "^3.0.2",
    "nativescript-intl": "^3.0.0",
    "nativescript-telerik-ui-pro": "2.0.0",
    "nativescript-unit-test-runner": "^0.3.2",
    "rxjs": "~5.3.0",
    "tns-core-modules": "3.0.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.0.0",
    "@ngtools/webpack": "1.3.0",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "chai": "^3.5.0",
    "codelyzer": "^3.0.0",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.1.0",
    "filewalker": "0.1.3",
    "karma": "^1.6.0",
    "karma-chai": "^0.1.0",
    "karma-mocha": "^1.3.0",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "mocha": "^3.3.0",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "^0.4.2",
    "nativescript-dev-webpack": "^0.4.0",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "tns-platform-declarations": "3.0.0",
    "tslint": "^5.1.0",
    "typescript": "~2.2.2",
    "webpack": "~2.4.1",
    "webpack-sources": "~0.2.3"
  },
```

### Please tell us how to recreate the issue in as much detail as possible.

Run any project or the [sdkAngular](https://github.com/telerik/nativescript-ui-samples-angular) from the Progress UI for NativeScript

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
No simply run a project tns run ios , the project needs to be in a path that somewhere contains space bars (example on Mac: _/Users/user1/Desktop/Work/**work projects**_)

**Comment by Alampalli-Yeshwanth** [comment]
I get this error when updated to 3.0.1

/Users/path/platforms/ios/Pods/MiniTabBar/MiniTabBar/Classes/MiniTabBarItemView.swift:101:44: error: value of optional type 'UIColor?' not unwrapped; did you mean to use '!' or '?'?
        return self.item.barBackgroundColor?
                                           ^
               (                            )!

** BUILD FAILED **


The following build commands failed:
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal x86_64 /Users/path/platforms/ios/Pods/MiniTabBar/MiniTabBar/Classes/MiniTabBar.swift
	CompileSwift normal x86_64 /Users/path/platforms/ios/Pods/MiniTabBar/MiniTabBar/Classes/MiniTabBarItemView.swift
(3 failures)
Multiple errors were thrown:
Command xcodebuild failed with exit code 65

**Comment by ivanbuhov** [comment]
Hi @Alampalli-Yeshwanth 
It seems that the `MiniTabBar` Pod you are using fails to compile. The compilation fails on the `MiniTabBar.swift` file. The problem may be in the Pod itself. You may find this [thread](https://stackoverflow.com/a/24877139/3968054) useful.
