### ISSUE TITLE
Command xcode build failed with exit code 65

### ISSUE THREAD

**Issue by PythonDevOp** [NativeScript/nativescript-cli#4163]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  5.0.0
 - Cross-platform modules: 5.0.3
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0
 - Plugin(s):   
    -     nativescript-angular: ~7.0.0
    -     nativescript-camera: ^4.1.1,
    -     nativescript-theme-core: ~1.0.4,
    -     nativescript-ui-listview: ^3.8.0,

MAC High Sierra 10.13.3
XCode: 9.0.1

**Describe the bug**
Error log:
> 
> Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
> Searching for devices...
> Executing before-liveSync hook from /Users/user/Documents/ngNative/hooks/before-liveSync/nativescript-angular-sync.js
> Executing before-watchPatterns hook from /Users/user/Documents/ngNative/hooks/before-watchPatterns/nativescript-dev-typescript.js
> Executing before-watchPatterns hook from /Users/user/Documents/ngNative/hooks/before-watchPatterns/nativescript-dev-webpack.js
> Executing before-watch hook from /Users/user/Documents/ngNative/hooks/before-watch/nativescript-dev-typescript.js
> Found peer TypeScript 3.1.6
> Executing before-watch hook from /Users/user/Documents/ngNative/hooks/before-watch/nativescript-dev-webpack.js
> Copying template files...
> Platform ios successfully added. v5.0.0
> Executing before-shouldPrepare hook from /Users/user/Documents/ngNative/hooks/before-shouldPrepare/nativescript-dev-webpack.js
> Executing before-prepare hook from /Users/user/Documents/ngNative/hooks/before-prepare/nativescript-dev-typescript.js
> Hook skipped because either bundling or livesync is in progress.
> Preparing project...
> Executing before-prepareJSApp hook from /Users/user/Documents/ngNative/hooks/before-prepareJSApp/nativescript-dev-webpack.js
> Successfully prepared plugin nativescript-angular for ios.
> Successfully prepared plugin nativescript-camera for ios.
> Successfully prepared plugin nativescript-theme-core for ios.
> Successfully prepared plugin nativescript-ui-listview for ios.
> Successfully prepared plugin tns-core-modules for ios.
> Successfully prepared plugin nativescript-intl for ios.
> nativescript-permissions is not supported for ios.
> Successfully prepared plugin nativescript-permissions for ios.
> Successfully prepared plugin nativescript-ui-core for ios.
> Successfully prepared plugin tns-core-modules-widgets for ios.
> Project successfully prepared (iOS)
> Executing after-prepare hook from /Users/user/Documents/ngNative/hooks/after-prepare/nativescript-dev-webpack.js
> Building project...
> Xcode build...
> === BUILD TARGET ngNative OF PROJECT ngNative WITH CONFIGURATION Debug ===
> ld: framework not found CoreServices for architecture i386
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ld: warning: linking ObjC for iOS Simulator, but dylib (/Users/user/Documents/ngNative/platforms/ios/internal/NativeScript.framework/NativeScript) was compiled for MacOSX
> ld: warning: linking ObjC for iOS Simulator, but dylib (/Users/user/Documents/ngNative/node_modules/nativescript-ui-listview/platforms/ios/TNSListView.framework/TNSListView) was compiled for MacOSX
> ld: warning: linking ObjC for iOS Simulator, but dylib (/Users/user/Documents/ngNative/node_modules/nativescript-ui-core/platforms/ios/TNSCore.framework/TNSCore) was compiled for MacOSX
> ld: warning: ObjC dylib (/Users/user/Documents/ngNative/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/TNSWidgets) was compiled for iOS Simulator, but dylibs others were compiled for MacOSX
> ld: framework not found CoreServices for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> === BUILD TARGET ngNative OF PROJECT ngNative WITH CONFIGURATION Debug ===
> error: the following command failed with exit code 1 but produced no further output
> Ld build/ngNative.build/Debug-iphonesimulator/ngNative.build/Objects-normal/x86_64/ngNative normal x86_64
> ** BUILD FAILED **
> 
> Unable to apply changes on device: BF6E776F-C30A-4908-9746-EB3DFF0A9317. Error is: Command xcodebuild failed with exit code 65.
> Executing after-watch hook from /Users/user/Documents/ngNative/hooks/after-watch/nativescript-dev-typescript.js
> Stopping tsc watch
> Executing after-watch hook from /Users/user/Documents/ngNative/hooks/after-watch/nativescript-dev-webpack.js
> Stopping webpack watch

**To Reproduce**

I created a new app via `tns create newApp --ng` and added the plugins above.

**Expected behavior**

**Sample project**

**Additional context**

App runs on Genymotion Android emulation, but does not run on IOS emulator.

**Comment by NickIliev** [comment]
@PythonDevOp the issue is most likely related to your XCode version. Try updating to XCode 10.

**Comment by Fatme** [comment]
@PythonDevOp,

Your problem might be related to this https://github.com/NativeScript/nativescript-cli/issues/3909

**Comment by PythonDevOp** [comment]
@NickIliev In order for me to upgrade to XCode 10, I'd have to update my Mac OS too. Not sure if I'd want to do that just for the sake of getting this working. Is there anything else I can try?

@Fatme I tried the steps mentioned [here](https://github.com/NativeScript/nativescript-cli/issues/3909#issuecomment-423789957) but that did not work. 

One thing I find interesting is the issue I am having (error code 65) seems to be present in issue #3909 as well, and one suggested solution to that is to _downgrade_ the XCode run version. I am slightly confused as to what the problem really is and what the best way to solve it is, but this problem appears to be a known one that more than 1 person has faced.

Any thoughts on the culprit? MY guess is that it has something to do with this, but I dont know what it means:
> ld: warning: ObjC dylib (/Users/user/Documents/ngNative/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework/TNSWidgets) was compiled for iOS Simulator, but dylibs others were compiled for MacOSX

**Comment by dtopuzov** [comment]
Hi @PythonDevOp,

Can you reproduce the problem on brand new hello world project without any plugins?

**Comment by alereisan** [comment]
I have Updated XCode from version 9.4 to 10.1
Still does not work.

Command xcodebuild failed with exit code 65

**Comment by dtopuzov** [comment]
Hi @alereisan,

Can you reproduce the issue in hello world app without plugins?

**Comment by alereisan** [comment]
@dtopuzov yes, i just made a new project in sidekick -> Angular & Typescript -> Blank

Tried running it on iPhone 6 (real device):

> [18-12-11 16:53:37.973] Error detected during LiveSync on a967568f06ab317c825eb0315604abe2cb9b4f3a for /Users/iamacpro2018/Documents/nativescript/CleanIOSBUildTest. Error: Command xcodebuild failed with exit code 65 Error output:
** ARCHIVE FAILED **

**Comment by alereisan** [comment]
@dtopuzov I just tried to run it in debug on iPhone XR Simulator.
On Simulator it runs without problem.

**Comment by PythonDevOp** [comment]
@dtopuzov - sorry, I haven't tried. Will try again today and let you know

**Comment by b-m-9** [comment]
Hello,
I'm having same issue with latest nativescript version(5.1.1) and xcode(10.1) with blank project.

**Comment by PythonDevOp** [comment]
@miroslavaivanova How would you like for me to send the log?

**Comment by miroslavaivanova** [comment]
@PythonDevOp you can drag and drop the file into the comment box.

**Comment by theRaffe** [comment]
hello do you know if nativescript 5.1.1 will work with Xcode 9.4 ??

I have the same problem

**Comment by ppico22** [comment]
[log.txt](https://github.com/NativeScript/nativescript-cli/files/2842454/log.txt)
Hello @miroslavaivanova im running into the same problem, i ran the project on the ios simulator with success, but this error comes up when i try to do it on my phone.

i ran the command to generate the .txt file and i´m attaching it.

**Comment by PythonDevOp** [comment]
@miroslavaivanova Please see the attached log:
[log.txt](https://github.com/NativeScript/nativescript-cli/files/2845995/log.txt)

**Comment by ppico22** [comment]
@miroslavaivanova i ran the tns debug command and i saw that the conflict was a dependecy on my package json file that was depracated i erased and i works.

**Comment by KristianDD** [comment]
Hi @PythonDevOp,
It seems that the version of your Xcode is very old. Please try upgrading Xcode to a newer version (10.1) and your NativeScript v5.x.x. project should build and run without any issues.

**Comment by PythonDevOp** [comment]
@KristianDD - Ok. I will try to update my OS to accommodate for the new XCode 10.1 version. Previously I was unable to due to security policy locally, but will try again.

**Comment by mgpepe** [comment]
I opened up XCode, there you can find details on what the error is. in my case some library was missing.

**Comment by mycomputerbooks** [comment]
Command failed with exit code 65
I am getting the same error. Here is my xcode read-out: 
duplicate symbol _OBJC_CLASS_$_CDVLogger in:
    /Users/mark_prouty/Library/Developer/Xcode/DerivedData/Ready_Hen-axfzmmdpaundclaokmdvuxsnrcmx/Build/Intermediates.noindex/Ready Hen.build/Debug-iphonesimulator/Ready Hen.build/Objects-normal/x86_64/CDVLogger.o
    /Users/mark_prouty/Library/Developer/Xcode/DerivedData/Ready_Hen-axfzmmdpaundclaokmdvuxsnrcmx/Build/Products/Debug-iphonesimulator/libCordova.a(CDVLogger.o)
duplicate symbol _OBJC_METACLASS_$_CDVLogger in:
    /Users/mark_prouty/Library/Developer/Xcode/DerivedData/Ready_Hen-axfzmmdpaundclaokmdvuxsnrcmx/Build/Intermediates.noindex/Ready Hen.build/Debug-iphonesimulator/Ready Hen.build/Objects-normal/x86_64/CDVLogger.o
    /Users/mark_prouty/Library/Developer/Xcode/DerivedData/Ready_Hen-axfzmmdpaundclaokmdvuxsnrcmx/Build/Products/Debug-iphonesimulator/libCordova.a(CDVLogger.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
===================
2 duplicate symbols for architecture x86_64
linker command faild with exit code 1 (use -v to see invocation)

![xcode](https://user-images.githubusercontent.com/37756739/57420638-07d34a00-71ce-11e9-8e63-23ba5d1c8f30.jpg)

**Comment by rosen-vladimirov** [comment]
Thanks guys, as this issue is quite old and contains different problems and solutions, I'm closing it. In case you have similar problem, please open a new issue.
